# Autogenerated wrapper script for libvofi_jll for i686-w64-mingw32
export libvofi

JLLWrappers.@generate_wrapper_header("libvofi")
JLLWrappers.@declare_library_product(libvofi, "libvofi.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libvofi,
        "bin\\libvofi.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
