# Autogenerated wrapper script for libvofi_jll for x86_64-apple-darwin
export libvofi

JLLWrappers.@generate_wrapper_header("libvofi")
JLLWrappers.@declare_library_product(libvofi, "@rpath/libvofi.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libvofi,
        "lib/libvofi.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
